[package]
name = "bombshell"
version = "0.1.0"
authors = ["Kris NÃ³va <kris@nivenly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
